# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sistema Financeiro.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
##-----------------------------------------------------------------------------------------##
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(701, 610)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Imgs/icon-financeiro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 210, 451, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(110, 0, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(22)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.TbwEmprestimos = QtWidgets.QTableWidget(Form)
        self.TbwEmprestimos.setGeometry(QtCore.QRect(10, 240, 681, 361))
        font = QtGui.QFont()
        font.setPointSize(12)

        self.TbwEmprestimos.setFont(font)
        self.TbwEmprestimos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TbwEmprestimos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TbwEmprestimos.setRowCount(1)
        self.TbwEmprestimos.setObjectName("TbwEmprestimos")
        self.TbwEmprestimos.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.TbwEmprestimos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TbwEmprestimos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TbwEmprestimos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TbwEmprestimos.setHorizontalHeaderItem(3, item)
        self.TbwEmprestimos.horizontalHeader().setDefaultSectionSize(166)
        self.TbwEmprestimos.horizontalHeader().setMinimumSectionSize(100)
        self.TbwEmprestimos.verticalHeader().setDefaultSectionSize(30)

        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 321, 161))
        self.groupBox.setObjectName("groupBox")
        self.CmbCredor = QtWidgets.QComboBox(self.groupBox)
        self.CmbCredor.setGeometry(QtCore.QRect(10, 40, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CmbCredor.setFont(font)
        self.CmbCredor.setAcceptDrops(False)
        self.CmbCredor.setObjectName("CmbCredor")
        self.CmbCredor.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.CmbDevedor = QtWidgets.QComboBox(self.groupBox)
        self.CmbDevedor.setGeometry(QtCore.QRect(10, 120, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CmbDevedor.setFont(font)
        self.CmbDevedor.setObjectName("CmbDevedor")
        self.CmbDevedor.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 40, 311, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.BtnConfirma = QtWidgets.QPushButton(self.groupBox_2)
        self.BtnConfirma.setGeometry(QtCore.QRect(10, 110, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BtnConfirma.setFont(font)
        self.BtnConfirma.setObjectName("BtnConfirma")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.TxbSenha = QtWidgets.QLineEdit(self.groupBox_2)
        self.TxbSenha.setEnabled(True)
        self.TxbSenha.setGeometry(QtCore.QRect(10, 40, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.TxbSenha.setFont(font)
        self.TxbSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.TxbSenha.setObjectName("TxbSenha")

        self.retranslateUi(Form)
        self.CmbCredor.setCurrentIndex(0)
        self.CmbDevedor.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.AddConnects()

        self.SetCmbItens()
        self.TbwEmprestimos.setColumnCount(4)
        self.SetTableContent()
##-----------------------------------------------------------------------------------------##
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Lista de Emprestimos relacionados entre credor e devedor:"))
        self.label_1.setText(_translate("Form", "Sistema de emprestimo financeiro!"))
        item = self.TbwEmprestimos.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Credor"))
        item = self.TbwEmprestimos.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Devedor"))
        item = self.TbwEmprestimos.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Data"))
        item = self.TbwEmprestimos.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Valor (R$)"))
        self.groupBox.setTitle(_translate("Form", "Usuarios:"))
        self.CmbCredor.setPlaceholderText(_translate("Form", "Selecione um Credor"))
        self.CmbCredor.setItemText(0, _translate("Form", "Selecione um Credor"))
        self.label_4.setText(_translate("Form", "Devedor:"))
        self.CmbDevedor.setPlaceholderText(_translate("Form", "Selecione um Devedor"))
        self.CmbDevedor.setItemText(0, _translate("Form", "Selecione um Devedor"))
        self.label_2.setText(_translate("Form", "Credor:"))
        self.groupBox_2.setTitle(_translate("Form", "Autenticação:"))
        self.BtnConfirma.setText(_translate("Form", "Confirmar"))
        self.label_3.setText(_translate("Form", "Senha do Credor:"))
##-----------------------------------------------------------------------------------------##
    def AddConnects(self):
        self.BtnConfirma.clicked.connect(self.SetTableContent)


    def SetCmbItens(self):
        usuarios = GetUsuarios()
        for usuario in usuarios:
            self.CmbCredor.addItem(usuario)
            self.CmbDevedor.addItem(usuario)
            

    def SetTableContent(self):
        emprestimos = GetEmprestimosRelacionados(self.CmbCredor.currentText(), self.CmbDevedor.currentText())
        self.TbwEmprestimos.setRowCount(len(emprestimos))
        for i, emprestimo in enumerate(emprestimos):
            self.TbwEmprestimos.setItem(i, 0, QtWidgets.QTableWidgetItem(emprestimo[0]))
            self.TbwEmprestimos.setItem(i, 1, QtWidgets.QTableWidgetItem(emprestimo[1]))
            self.TbwEmprestimos.setItem(i, 2, QtWidgets.QTableWidgetItem(emprestimo[2]))
            self.TbwEmprestimos.setItem(i, 3, QtWidgets.QTableWidgetItem(str(emprestimo[3])))
        self.TbwEmprestimos

            
    


##-----------------------------------------------------------------------------------------##



def GetUsuarios():
    return ["maria","joao","claudia","marcos","dede do dodo da dada di didi"]

def GetEmprestimosRelacionados(credor, devedor):
    emprestimos = GetEmprestimos()
    emprestimosRelacionados = []
    for emprestimo in emprestimos:
        if emprestimo[0] == credor and emprestimo[1] == devedor:
            emprestimosRelacionados.append(emprestimo)
    return emprestimosRelacionados

def GetEmprestimos():
    return [["maria", "joao", "diatal", 53], ["claudia", "marcos", "diaoutro", 23], ["maria", "marcos", "diatal", 53], ["maria", "joao", "diaoutro", 25], ["dede do dodo da dada di didi", "maria", "diatdfal", 535]]


##*****************************************************************************************##
def StartApplication():
    import sys
    ApplicationInstance = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QWidget()
    UiDesign = Ui_Form()
    UiDesign.setupUi(Window)
    Window.show()
    sys.exit(ApplicationInstance.exec_())


if __name__ == "__main__":
    StartApplication()